source 'https://rubygems.org'



  gem 'selenium-webdriver', '~>3.10.0'
  gem 'rspec', '~> 3.3.0'
  gem 'rspec-expectations'
  gem 'rspec-retry'
  gem 'capybara'
  gem 'nokogiri', '~> 1.8.1'
  gem 'chromedriver-helper', '0.0.8'
  gem 'geckodriver-helper'
  gem 'poltergeist', '1.6.0'
  gem 'smarter_csv', '1.0.19'
  gem 'json-schema', '2.6.2'
  gem 'require_all'
  gem 'cucumber'
  gem 'site_prism'
  gem 'site_prism-table'
  gem 'rspec-support', '~> 3.3'
  gem 'parallel_tests'
  gem 'cmdparse', '~> 3.0', '>= 3.0.3'
  gem 'rake-rspec'
  gem 'parallel_rspec'
  gem 'faker'
  gem 'launchy'
  gem 'activesupport', '~> 5.0', '>= 5.0.0.1'
  gem 'money'
  gem 'rspec_html_formatter','~> 0.3.1'
  gem 'parallel_split_test'
  gem 'yarjuf'
  gem 'danger-junit'
  gem 'rspec_junit_formatter'